set -x
curl \
  --header "Authorization: Bearer eFzdK7eYeDr3dQ.atlasv1.gTbORMzanGi97xson6NzPs1ScnifTviNZeTcWMK65I7ONgSxMOrMy0XeW4WduzGyhSw" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @post.json \
  https://app.terraform.io/api/v2/organizations/Flexera-SE/workspaces

 https://archivist.terraform.io/v1/object/dmF1bHQ6djE6dS9EeENnL3FEWDhWRFNxMGlWYjk5ZDkvNjBJSWhvdzRXTEJVY2wxOHRFMHRveldhU29PQVE5RHZSM2xDemFRRjNqN0owUzZSVE8rRDNsYjdiYU1GUW52MGp2eGY3R1pCaHNRQWYzMStDSDV0UDd0MStUS21Oak93dUVzMGpnZldCVUF0VlNYcEd0MG5YcUlWdExZRVVpWmozWUpMeW5jVk5ndWpIVk52VlphOGMrbGtuWGVXY0Zvc2RDaVhMRk80WEVNZDZ2cVIzeC9wUXRQOElYMGUwTXZuSzljdjdIS056TU9pRU8vTTVrU3o1ZEc5Mm9EV1RuZ0VoRFVOLy9Ia3hNTmN6aHBOSGlFVWhzQVlVZER1TUhOV2hUV05tZEZmVlVvc0FPZDFPaExnTTVpV0F4cG9yTlBnQm5yM2hJRTVTNFUzTHJLb2dtaDZ4RFhPb2prNzZLNWhkMzNqeDE5RGowQ0x0UzJIVWpyODZ3PT0
StagingRSCMP1!!